header:
  version: 11

distro: poky
target: core-image-base

local_conf_header:
  dev-config: |
    PACKAGE_CLASSES ?= "package_deb"
    USER_CLASSES ?= "buildstats"
    
    # Shared download and state folder
    DL_DIR = "/workspace/downloads"
    SSTATE_DIR = "/workspace/sstate-cache"

    # Enable security features
    DISTRO_FEATURES:append = " security"

    # Enable systemd as init manager
    INIT_MANAGER = "systemd"

    # Enable CVE monitoring
    INHERIT += "cve-check"
